#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  gains:
    joint_1: {p: 100, i: 0.01, d: 1}
    joint_2: {p: 100, i: 0.01, d: 1}
    joint_3: {p: 100, i: 0.01, d: 1}
    joint_4: {p: 100, i: 0.01, d: 1}
    joint_5: {p: 100, i: 0.01, d: 1}
    joint_6: {p: 100, i: 0.01, d: 1}

  constraints:
    goal_time: 10.0                  # Override default

  state_publish_rate:  50            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default

#Controller to control end effector joints
hand_ee_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [right_ee_joint, left_ee_joint]
  
  gains:
    right_ee_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
    left_ee_joint: {p: 100, i: 1, d: 10, i_clamp: 1.0}
  constraints:
    goal_time: 3.0
    right_ee_joint:
      goal: 0.02
    left_ee_joint:
      goal: 0.02

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
